//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.DetailsOrders = new HashSet<DetailsOrder>();
        }
    
        public int ID_SanPham { get; set; }
        public Nullable<int> ID_DanhMuc { get; set; }
        public string TenSanPham { get; set; }
        public string HinhAnh { get; set; }
        public string MaSanPham { get; set; }
        public Nullable<int> GiaGoc { get; set; }
        public string Sale { get; set; }
        public string TinhTrang { get; set; }
        public string Video { get; set; }
        public string HinhAnhGame { get; set; }
        public string HinhAnhGame1 { get; set; }
        public string HinhAnhGame2 { get; set; }
        public string MoTa { get; set; }
        public string MoTa1 { get; set; }
        public string MoTa2 { get; set; }
        public string Tags { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailsOrder> DetailsOrders { get; set; }
    }
}
